config/routes.rb
Rails.application.routes.draw do
  get 'products/create'
  root to: 'categories#index'

  resources :categories, only: [:index, :create, :show ] do
    resources :products, only: [:new]
  end

  # resources :products, only: [:create]
resources :products, only: [:create] do
    resources :product_categories, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories

  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
 has_many :product_categories
 has_many :categories, through: :product_categories

 validates :title, :description, presence: true
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @product = Product.new
  end

  def create
    @categories = Category.all
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :index
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def create
    @product = Product.new(product_params)
    selected_categories = params[:product][:categories]
    if @product.save
      if selected_categories
        selected_categories.each do |id|
          category = Category.find(id)
          product_category = ProductCategory.create(product: @product, category: category)
        end
        redirect_to category_path(@product.categories.first)
      else
        # Needed if no categories is selected on the form
        redirect_to new_product_path
      end
    else
      render :new
    end
  end

  def new
    @product = Product.new

  end

  private

  def product_params
    params.require(:product).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.haml
.centered
  %h1 Categories
  - @categories.each do |category|
    %p.green
      🍼 #{link_to category.name, category_path(category)}
  .form-container
    %h4.green Create a new category
    = simple_form_for @category do |f|
      = f.input :name
      .button-container= f.button :submit, class: "button"

app/views/categories/show.html.haml
.centered
  %h1
    Products for #{@category.name}
  - @category.products.order(created_at: :desc).each do |product|
    %p.green
      🍼 #{product.title}
    %p
      = product.description
    %p= product.created_at.strftime("%m/%d/%Y")
  .button-container
    %span.button= link_to "Create a new product", new_category_product_path(@category)
    %span.button= link_to "Back to Categories", categories_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "UTF-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title TODO
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    / Uncomment if you import CSS in app/javascript/packs/application.js
  %body
    = yield
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application'

app/views/products/new.html.haml
.centered
  %h1 Create a product
  .form-container
    = simple_form_for @product do |f|
      = f.input :title
      = f.input :description
      %p Please select at least one category below
      = f.input :categories, as: :check_boxes, collection: Category.all, include_hidden: false, checked: params[:category_id]
      = f.button :submit, class: "button"